GET http://localhost:3001/api/blogs

###

DELETE http://localhost:3001/api/blogs/638b97a6dc92478f889dcfdd


###

PUT http://localhost:3001/api/blogs/id:

###

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
      "username": "samson667",
      "name": "samson667",
      "password": "samson667"
}





